version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  cars: 
    image: cars:latest
    container_name: cars
    pull_policy: never 
    build: 
      args:
        SERVICE: cars
    environment: 
      STORAGE_CONN_STRING: ${CARS_STORAGE_CONN_STRING}
    restart: on-failure
    ports: 
      - "8070:8070"

  rental: 
    image: rental:latest
    container_name: rental
    pull_policy: never 
    build: 
      args:
        SERVICE: rental 
    restart: on-failure
    ports: 
      - "8060:8060"

  payment: 
    image: payment:latest
    container_name: payment
    pull_policy: never 
    build: 
      args:
        SERVICE: payment 
    restart: on-failure
    ports: 
      - "8050:8050"

  gateway: 
    image: gateway:latest
    container_name: gateway
    pull_policy: never 
    build: 
      args:
        SERVICE: gateway 
    environment:
      CARS_SERVICE_URL: http://cars:8070/api/v1/cars/
    restart: on-failure
    ports: 
      - "8080:8080"

volumes:
  db-data: